improve build_and_update script

diff --git a/build_and_update b/build_and_update
--- a/build_and_update
+++ b/build_and_update
@@ -1,4 +1,19 @@
 #!/bin/sh
-rpmbb opengt.spec && \
-sudo rpm -Uhv $HOME/RPM/RPMS/i586/*opengt*.i586.rpm $HOME/RPM/RPMS/i586/osolutions-webapps-agp-*.i586.rpm
+VERSION=`cat opengt.spec|grep Version|awk -F': ' '{ print $2; }'`
+RELEASE=`cat opengt.spec|grep Release|awk -F': ' '{ print $2; }'`
+FILES=`ls -1 $HOME/RPM/RPMS/i586/*opengt*$VERSION-$RELEASE.i586.rpm $HOME/RPM/RPMS/i586/osolutions-webapps-agp-*$VERSION-$RELEASE.i586.rpm`
+rpmbb opengt.spec || (echo "Build failed. Exit."; exit 1)
+rpm -q opengtd && sudo rpm -Uhv $FILES || sudo rpm -ihv $FILES
 sudo service nginx restart
+
+if [ "$1" = "server" ]; then
+	scp $FILES map.spo:/tmp/
+	ssh="ssh map.spo"
+	echo "Update rpm"
+	$ssh 'sudo rpm -Uhv /tmp/*.rpm'
+	echo "Remove rpm"
+	$ssh 'sudo rm -f /tmp/*.rpm'
+	echo "Restart nginx"
+	$ssh 'sudo service nginx restart'
+	git push spo
+fi
